apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
spec:
  {{ if eq .Values.version "v1" }}
  type: NodePort
  {{ end }}
  ports:
    - name: "result-service"
      port: 5000
      targetPort: 5000
      {{ if eq .Values.version "v1" }}
      nodePort: 31001
      {{ end }}
  selector:
    app: result
