{{ if ne .Values.version "v1" }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote-ui
  name: vote-ui
spec:
  type: NodePort
  ports:
    - name: "vote-ui-service"
      port: 80
      targetPort: 80
      nodePort: 31000
  selector:
    app: vote-ui
{{ end }}
