{{ if ne .Values.version "v3" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - image: {{ .Values.registry }}/worker:{{ .Values.worker.language }}
          name: worker
          imagePullPolicy: Always
{{ end }}
