apiVersion: v1
kind: Service
metadata:
  name: vote
spec:
  type: ClusterIP
  ports:
    - name: "vote-service"
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  type: ClusterIP
  ports:
    - name: "result-service"
      port: 80
      targetPort: 80
