apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitlab.com/voting-application/config.git
    targetRevision: master
    path: apps/traefik
    plugin: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
