apiVersion: v1
kind: Service
metadata:
  labels:
    app: result-ui
  name: result-ui
spec:
  type: NodePort
  ports:
    - name: "result-ui-service"
      port: 5001
      targetPort: 80
      nodePort: 31001
  selector:
    app: result-ui
